package com.bizflow.cloud.ui.theme

import androidx.compose.ui.graphics.Color

// Marca principal (idêntica ao web: Tailwind blue-600)
val BrandPrimary = Color(0xFF2563EB)

// Semânticos de negócio (idênticos ao web)
val IncomeGreen = Color(0xFF22C55E)
val ExpenseRose = Color(0xFFF43F5E)

// Acents dos gráficos (idênticos ao web)
val ChartViolet = Color(0xFF8B5CF6)
val ChartFuchsia = Color(0xFFD946EF)
val ChartLime = Color(0xFF84CC16)
val ChartOrange = Color(0xFFF97316)
val ChartAmber = Color(0xFFEAB308)

// Light scheme (essência web: fundo slate-100, cartões brancos, slate neutros)
val LightPrimary = Color(0xFF2563EB)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDBEAFE)
val LightOnPrimaryContainer = Color(0xFF1E40AF)
val LightSecondary = Color(0xFF475569)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE2E8F0)
val LightOnSecondaryContainer = Color(0xFF1E293B)
val LightTertiary = Color(0xFF7C3AED)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFEDE9FE)
val LightOnTertiaryContainer = Color(0xFF4C1D95)
val LightError = Color(0xFFDC2626)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFEE2E2)
val LightOnErrorContainer = Color(0xFF7F1D1D)
val LightBackground = Color(0xFFF1F5F9)
val LightOnBackground = Color(0xFF0F172A)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF0F172A)
val LightSurfaceVariant = Color(0xFFE2E8F0)
val LightOnSurfaceVariant = Color(0xFF475569)
val LightOutline = Color(0xFF94A3B8)
val LightOutlineVariant = Color(0xFFCBD5E1)
val LightScrim = Color(0xFF000000)
val LightInverseSurface = Color(0xFF0F172A)
val LightInverseOnSurface = Color(0xFFF1F5F9)
val LightInversePrimary = Color(0xFF60A5FA)

// Dark scheme (essência web: fundo slate-900, primária azul-400)
val DarkPrimary = Color(0xFF60A5FA)
val DarkOnPrimary = Color(0xFF002F6C)
val DarkPrimaryContainer = Color(0xFF1E40AF)
val DarkOnPrimaryContainer = Color(0xFFDBEAFE)
val DarkSecondary = Color(0xFF94A3B8)
val DarkOnSecondary = Color(0xFF1E293B)
val DarkSecondaryContainer = Color(0xFF334155)
val DarkOnSecondaryContainer = Color(0xFFE2E8F0)
val DarkTertiary = Color(0xFFA78BFA)
val DarkOnTertiary = Color(0xFF3B0764)
val DarkTertiaryContainer = Color(0xFF6D28D9)
val DarkOnTertiaryContainer = Color(0xFFEDE9FE)
val DarkError = Color(0xFFF87171)
val DarkOnError = Color(0xFF7F1D1D)
val DarkErrorContainer = Color(0xFFB91C1C)
val DarkOnErrorContainer = Color(0xFFFEE2E2)
val DarkBackground = Color(0xFF0F172A)
val DarkOnBackground = Color(0xFFF1F5F9)
val DarkSurface = Color(0xFF0F172A)
val DarkOnSurface = Color(0xFFF1F5F9)
val DarkSurfaceVariant = Color(0xFF1E293B)
val DarkOnSurfaceVariant = Color(0xFF94A3B8)
val DarkOutline = Color(0xFF64748B)
val DarkOutlineVariant = Color(0xFF334155)
val DarkScrim = Color(0xFF000000)
val DarkInverseSurface = Color(0xFFE2E8F0)
val DarkInverseOnSurface = Color(0xFF0F172A)
val DarkInversePrimary = Color(0xFF2563EB)